import transactionAPI from "./api";

import { ITransaction } from "../../../../server/src/models/Transaction";

const transactionCategories = [
  "housing",
  "transport",
  "health",
  "education",
  "leisure",
  "savings",
  "utilities",
  "income",
  "donations",
  "subscriptions",
  "pets",
  "clothing",
  "personal_care",
  "taxes",
  "gifts",
  "business",
  "home_supplies",
  "childcare",
  "insurance",
  "debt",
  "events",
  "technology",
  "legal",
  "relocation",
  "environment",
  "side_hustles",
  "investments",
  "repair",
  "hospitality",
  "banking",
];

const transactionSubcategories = {
  housing: [
    "rent",
    "mortgage",
    "property_tax",
    "home_insurance",
    "repairs",
    "hoa_fees",
    "furnishing",
  ],
  transport: [
    "fuel",
    "public_transport",
    "car_maintenance",
    "parking",
    "ride_sharing",
    "vehicle_registration",
    "tolls",
  ],
  health: [
    "medical",
    "dental",
    "vision",
    "health_insurance",
    "mental_health",
    "medications",
    "therapy",
  ],
  education: [
    "tuition",
    "books",
    "supplies",
    "courses",
    "online_learning",
    "exam_fees",
    "certifications",
  ],
  leisure: [
    "entertainment",
    "hobbies",
    "vacation",
    "concerts",
    "games",
    "movies",
    "sports",
  ],
  savings: [
    "emergency_fund",
    "retirement",
    "investments",
    "travel_savings",
    "education_savings",
    "big_purchase_savings",
  ],
  utilities: [
    "electricity",
    "water",
    "gas",
    "internet",
    "trash_collection",
    "phone_plan",
    "sewage",
  ],
  income: [
    "salary",
    "bonus",
    "side_income",
    "freelance",
    "rental_income",
    "royalties",
  ],
  donations: ["charity", "gifts", "fundraisers", "church", "nonprofit_support"],
  subscriptions: [
    "streaming_services",
    "magazines",
    "software",
    "newsletters",
    "cloud_storage",
    "memberships",
  ],
  pets: [
    "food",
    "veterinary_care",
    "grooming",
    "toys",
    "adoption_fees",
    "insurance",
  ],
  clothing: [
    "apparel",
    "accessories",
    "footwear",
    "formal_wear",
    "seasonal_clothing",
    "tailoring",
  ],
  personal_care: [
    "cosmetics",
    "haircuts",
    "spa",
    "massage",
    "skincare",
    "gym_membership",
  ],
  taxes: [
    "income_tax",
    "property_tax",
    "self_employment_tax",
    "tax_preparation_fees",
  ],
  gifts: ["birthdays", "holidays", "weddings", "anniversaries", "graduations"],
  business: [
    "supplies",
    "services",
    "software",
    "travel",
    "consulting",
    "marketing",
  ],
  home_supplies: [
    "furniture",
    "appliances",
    "cleaning_supplies",
    "decorations",
    "tools",
  ],
  childcare: ["daycare", "school_supplies", "clothing", "toys", "activities"],
  insurance: [
    "auto_insurance",
    "life_insurance",
    "home_insurance",
    "health_insurance",
    "travel_insurance",
  ],
  debt: [
    "credit_card_payments",
    "loans",
    "student_loans",
    "mortgage_payments",
    "debt_consolidation",
  ],
  events: ["weddings", "parties", "birthdays", "anniversaries", "conferences"],
  technology: ["gadgets", "software", "hardware", "repairs", "subscriptions"],
  legal: ["consultations", "documents", "court_fees", "legal_retainer"],
  relocation: [
    "moving_costs",
    "storage",
    "travel_expenses",
    "new_rent_deposit",
  ],
  environment: [
    "sustainable_products",
    "donations",
    "carbon_offsetting",
    "recycling_services",
  ],
  side_hustles: [
    "freelancing_income",
    "product_sales",
    "affiliate_income",
    "services_rendered",
  ],
  investments: ["stocks", "bonds", "crypto", "real_estate", "mutual_funds"],
  repair: [
    "home_repair",
    "car_repair",
    "appliance_repair",
    "electronics_repair",
  ],
  hospitality: ["restaurants", "hotels", "bars", "cafes", "tips"],
  banking: [
    "fees",
    "interest_charges",
    "atm_withdrawals",
    "wire_transfers",
    "account_maintenance",
  ],
};

export type { ITransaction };
export default { transactionAPI, transactionCategories, transactionSubcategories };
